repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.11
    hooks:
    - id: mdformat
      additional_dependencies:
      - mdformat-gfm
      - mdformat-tables
      - mdformat-beautysh
      - mdformat-black

  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
